### ISSUE TITLE
Cardboard library is not recognised

### ISSUE THREAD

**Issue by shashankbl** [codeanticode/processing-cardboard#1]
@codeanticode : Kindly help me with this issue.
OS: Windows 10
Processing: 3.1.2 Android Mode: 4.0-beta2

Downloaded the zipped repository and unpacked it. Copied the folder as 'processing-cardboard' and copied it into libraries folder for Processing. Even after restart of Processing, unable to import the library.
Other manual library installations are recognized.

Tried renaming the folder to 'cardboard' as well. Same issue persists.
Following is the screenshot from Processing IDE:

![image](https://cloud.githubusercontent.com/assets/5702511/17801788/5bfe06d0-65a9-11e6-83d7-054f2d8950fa.png)

**Comment by hype** [comment]
@shashankbl probably because you clicked the "Clone or download" button from the master repo... rather than visiting here : https://github.com/codeanticode/processing-cardboard/releases/tag/latest / @codeanticode I'd suggest adding a link to the latest in the README.md

**Comment by codeanticode** [comment]
@hype thanks for the suggestion, added installation instructions to the README.
