### ISSUE TITLE
3D Camera placement doubt

### ISSUE THREAD

**Issue by omaribraz** [codeanticode/processing-cardboard#2]
Its not really an issue, Everything is working great. Just wanted to know how the camera postition. From trial and error I found its around (0,0,600). Just wanted the actual number for a code I am writing. 

I think you place a camera in the source library. What is the value of cameraZ?

`camera(0.0f, 0.0f, cameraZ, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f);`

Anyway thanks for this library its amazing 😀  👍

**Comment by codeanticode** [comment]
Hi, sorry I'm completely missed your question. The camera placement is determined by Processing depending on the size of the output screen. You can get this value using the cameraZ variable like so:

void draw()
  float camDist = ((PGraphicsOpenGL)g).cameraZ; 
  println(camDist);
}
